[".vim/pack/other/opt/lsp"]
type = "git-repo"
url = "https://github.com/yegappan/lsp"

[".vim/pack/other/start/commentary"]
type = "git-repo"
url = "https://github.com/tpope/vim-commentary"

[".vim/pack/other/start/editorconfig-vim"]
type = "git-repo"
url = "https://github.com/editorconfig/editorconfig-vim"

[".vim/pack/other/start/fugitive"]
type = "git-repo"
url = "https://github.com/tpope/vim-fugitive"

[".vim/pack/other/start/fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf"

[".vim/pack/other/start/fzf.vim"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.vim"

[".vim/pack/other/start/nerdtree"]
type = "git-repo"
url = "https://github.com/preservim/nerdtree"

[".vim/pack/other/start/surround"]
type = "git-repo"
url = "https://github.com/tpope/vim-surround"

[".vim/pack/other/start/vim-airline"]
type = "git-repo"
url = "https://github.com/vim-airline/vim-airline"

[".vim/pack/other/start/vim-gitgutter"]
type = "git-repo"
url = "https://github.com/airblade/vim-gitgutter"

[".vim/pack/syntax/start/rust.vim"]
type = "git-repo"
url = "https://github.com/rust-lang/rust.vim"

[".vim/pack/themes/opt/onedark"]
type = "git-repo"
url = "https://github.com/joshdick/onedark.vim"
